### ISSUE TITLE
Image service integration

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#6] opened 2020-01-16 09:44 UTC
Need to review how multimedia is handled with pipelines ingestion and possibly make changes to image-service API if required to accomodate a different workflow.

It may make sense to have the loading of images as a separate pipeline that is ran after the main record ingestion pipeline to accomodate the fact that image loading is slow in comparison to record loading due to the time required to download images.

**Comment by djtfmartin** [comment] 2020-04-06 16:26
GBIF's approach to images differs from ALAs in that they only run an on-demand cache of images. 
In addition, for a number of ALA data providers, the images are not provided to ALA via a URL, and we have in the past loaded images into the image-service.

For GBIF, references to external URLs are stored in AVRO and indexed into ES, and these references are only used to download the image when a user accesses the image in gbif.org. GBIF have previous supported a process of priming the image cache, but they have moved away from this due to complaints from data providers (bandwidth issues, crashing servers etc). They have a larger number of data providers to deal with, so handling bandwidth issues with providers is a bigger issue for GBIF.

The pipelines transforms that are currently implemented in GBIF pipelines just process the image/multimedia/audobon metadata extensions. They don't actually trigger a download of the image artefacts themselves.

**Comment by javier-molina** [comment] 2020-04-23 07:15
@djtfmartin, @sadeghim is #50  a duplicate of this or a separate concern on its own?

**Comment by djtfmartin** [comment] 2020-04-23 07:40
thanks @javier-molina 
This is a separate concern. This issue is more about how pipelines interfaces with image-service. 
#50 is about exporting existing image references into DwCA to load into pipelines.

**Comment by sadeghim** [comment] 2020-09-03 07:00
We need to check the performance of loading images (whether they exist on image-service or not). My concern is that it will be very slow even when the images are already on the image-server.  And to tackle that we may need to have a key-value store for `imageIdentifier<->imageUuid` and maybe the whole image metadata to be available for the indexing next time.
This will happen very often for iNat (which is a weekly job) with around a million images.

**Comment by djtfmartin** [comment] 2020-11-05 15:03
This is now ready for review. There are 2 pull requests for this issue:

* Image service: https://github.com/AtlasOfLivingAustralia/image-service/pull/118
* Pipelines: https://github.com/gbif/pipelines/pull/413

**Comment by djtfmartin** [comment] 2020-11-27 15:11
This is done and merged.

**Closed** 2021-01-13 02:44 UTC
Labels: effort-xlarge, enhancement, epic
