### ISSUE TITLE
Viewing record page with invalid ID should show 404 but gives application error

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#430] opened 2021-06-21 04:26 UTC
If I modify the URL for a record page by adding or removing values from the UUID, I expect to see a `record not found` warning - which I do see on prod:

![image](https://user-images.githubusercontent.com/532845/122707023-800d0480-d29c-11eb-8392-19cd99732897.png)

On test I get a different error:

![image](https://user-images.githubusercontent.com/532845/122707073-9adf7900-d29c-11eb-98b4-9a905ec0077a.png)

I think test should behave the same way as prod.

**Comment by javier-molina** [comment] 2021-06-21 10:50
The service now returns a 404.

Biocache hub needs to be updated to use the new API which is more consistent with REST design principles.

**Comment by nickdos** [comment] 2021-06-21 22:21
When returning a `404`, the service is not be returning a JSON response (it is sending it as `text/html). I think the service should be returning the `message` in JSON format, if the request content-type is `application/json`, even when the status is `404` or `500`. Doing a bit of googling, it seems a common response content-type is `application/problem+json`, which can be handled by a JSON parser.

Either way, this is minor and can be marked for next release after next.

**Comment by nickdos** [comment] 2021-06-22 03:31
Same thing reported here https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/437

**Comment by alexhuang091** [comment] 2021-06-28 05:08
fixed in https://github.com/AtlasOfLivingAustralia/biocache-service/commit/d519339be2f34aa6ca10ada05498d30cf779f3a8

**Comment by javier-molina** [comment] 2021-06-30 06:32
@nickdos could you review this please, it might be that there is a related issue laying around biocache-service#587

**Comment by alexhuang091** [comment] 2021-06-30 06:46
> @nickdos could you review this please, it might be that there is a related issue laying around biocache-service#587

Hi Javier, don't worry. #587 is not related to this.

**Comment by nickdos** [comment] 2021-06-30 07:02
I think it is the same as #587. 

> When returning a 404, the service is not returning a JSON response (it is sending it as text/html). I think the service should be returning the message in JSON format

**Comment by alexhuang091** [comment] 2021-06-30 07:08
> I think it is the same as #587.
> 
> > When returning a 404, the service is not returning a JSON response (it is sending it as text/html). I think the service should be returning the message in JSON format

hi Nick, the root cause of this issue is, the function is supposed to return an object so it could be converted to JSON. 
But in reality, it returns a `null` which makes biocache-hubs failed to parse with `JSON.parse`  

The fix is just to return an empty Map when nothing is found.

**Comment by nickdos** [comment] 2021-06-30 07:15
I think Dave or Bruce changed the service to return `404` for when no record was found (which is the REST way to do it). This was a deliberate change. Does your change still give a HTTP `404` or does it return `200`?

**Comment by nickdos** [comment] 2021-06-30 07:24
I'm wondering if we should establish a pattern for this and other endpoints that follows a convention of sending `404` status code and then a meaningful message, like:

```json
{ 
  "status": 404,
  "message": "The requested record ID was not found"
}
```

@djtfmartin - your call on whether we just make it backwards compatible (return an empty object) or try and be more REST like in handling a "record not found" response with meaningful message.

**Comment by djtfmartin** [comment] 2021-06-30 07:34
+1 for the more REST like in handling a "record not found" response with meaningful message.

**Comment by alexhuang091** [comment] 2021-06-30 08:08
Hi Nick,

I changed the code just to make it same as on the prod.

1. on develop branch, /ws/occurrence/invalid_id gets a `200` response, `{}` in response body.
2. so on pipeline branch, with my change, `200` returned with `{}` in the response body
3. before my change, `null` is returned, so on biocache-hubs side, it failed to parse JSON body.

I don't know if any changes made yet to return `404` in case no record found. When I did the fix, `null` is found from controller.

**Comment by djtfmartin** [comment] 2021-07-08 12:12
@nickdos @alexhuang091 It looks like we have reverted to the functionality of old - which we agreed was wrong.

An invalid URL is now return a `200` and a blank response in test environment.
Can we change to `404` with sensible JSON response instead ?

**Comment by nickdos** [comment] 2021-07-08 23:42
> An invalid URL is now return a 200 and a blank response in test environment.
Can we change to 404 with sensible JSON response instead ?

+1

**Comment by RobinaSanderson** [comment] 2021-07-13 05:55
I tested this by:

1. viewing this record https://biocache-dq-test.ala.org.au/occurrences/cfa019f1-a51e-45dd-9311-e3213ace4c4b
2. adding 44 to the end of the URL
3. Error message returned is this: 
![image](https://user-images.githubusercontent.com/23368496/125398478-b698f380-e3f2-11eb-91c1-27c127d42b6b.png)

**Comment by alexhuang091** [comment] 2021-07-13 06:00
> I tested this by:
> 
> 1. viewing this record https://biocache-dq-test.ala.org.au/occurrences/cfa019f1-a51e-45dd-9311-e3213ace4c4b
> 2. adding 44 to the end of the URL
> 3. Error message returned is this:

Thanks Robina, this needs changes for both biocache-service (already merged) and biocache-hubs (not yet approved/merged).

To verify the changes for biocache-service you can visit https://nci3-biocache-service.ala.org.au/ws/occurrences/cfa019f1-a51e-45dd-9311-e3213ace4c4bdd-invalid, if you see "message": "Unrecognised UID" that means the change is in place.

**Comment by nickdos** [comment] 2021-07-14 00:51
Now shows expected output (same as pre-pipelines):

![image](https://user-images.githubusercontent.com/532845/125543636-19771d03-e58d-477e-8454-562cdd81eea5.png)

**Comment by nickdos** [comment] 2021-07-14 02:00
This change has broken facets display for some reason, so moving back into "in progress" to fix that...

![image](https://user-images.githubusercontent.com/532845/125548703-3ebceada-5ce1-4b74-95c0-d2a3e12a54f1.png)

**Comment by nickdos** [comment] 2021-07-14 06:03
Facets now fixed... so moving to done (again).

**Closed** 2021-07-26 03:47 UTC
Labels: biocache-hub, biocache-service, bug, testing-findings
