### ISSUE TITLE
Spatial portal - Add facet - facet options not displaying

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#316] opened 2021-04-29 07:35 UTC
**Steps to recreate**
1.	Add species layer to spatial portal – species = Eudyptula minor; Area = Australia; spatially valid records saved session: https://nectar-spatial-test.ala.org.au?ss=1619681852234 
2.	Select Add to map – Facet from the Add to map menu
3.	In the Facet field select Decade
Loading bar displays but no options load
Checked and Production is working.

**Notes:** 
•	If you choose Facet in the layer options pane (left of the map pane) the Decade options will show.
•	I checked with the basis of record facet and got the same issue
•	In Pipelines the facet name is “Basis of Record” in Production the facet name is “Record Type”

**Comment by djtfmartin** [comment] 2021-04-29 13:51
These issues seem to be related to Qid storage and retrieval issues.

**Comment by javier-molina** [comment] 2021-05-10 07:16
Could this be related so #337. I can still reproduce the issue.

**Comment by adam-collins** [comment] 2021-05-10 09:43
If qids are dropped from Cassandra nectar-spatial-test needs a restart to forget the deleted qids.

**Comment by adam-collins** [comment] 2021-05-10 10:28
Something fixed it since this test.

Related issue fixed with a backwards compatible config change. Because this is SOLR schema related I won't change biocache-service. https://github.com/AtlasOfLivingAustralia/spatial-hub/tree/pipelines

**Comment by adam-collins** [comment] 2021-05-18 07:52
can be retested

**Comment by qifeng-bai** [comment] 2021-06-01 00:22
It works on Spatial-test

**Closed** 2021-06-25 04:35 UTC
Labels: spatial-portal, testing-findings
