### ISSUE TITLE
improve recordedBy parsing

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/la-pipelines#391] opened 2021-06-01 03:50 UTC
currently `"raw_recordedBy":"Allen, G.R. & Robertson, D."` parses as `"recordedBy":["Allen", ", G.R.", "Robertson", ", D."]`, 4 values instead of 2.

Related: Searching for records via [`collector_text:remedios`](https://biocache.ala.org.au/occurrences/search?q=collector_text%3Aremedios) results in no records but using equivalent [`identifiedBy` field](https://biocache.ala.org.au/occurrences/search?q=text_identifiedBy%3Aremedios) returns the iNaturalist records I have created. Looking at those records, they show my name in both the collector (`recordedBy`) and `identifiedBy` fields. Investigate why `collector_text:remedios` does not return any records.

Example record: https://biocache.ala.org.au/occurrences/2600b767-e4bd-4360-b616-7913799e4516

**Comment by javier-molina** [comment] 2021-06-02 02:20
Not a showstopper so we can revisit this later on

**Comment by nickdos** [comment] 2021-08-17 00:46
Another user story to test, reported by a user. 

> As an iNat user
I want to view all my records on the ALA
So that I can check which records have gone through to the ALA or not

The user typed their iNat user name into the simple search box and this used to show all their records. With new version (Pipelines), this no longer works and results in zero records returned. E.g. try `nickdos` if testing.

**Comment by adam-collins** [comment] 2021-08-17 01:22
https://github.com/gbif/pipelines/pull/580

**Comment by javier-molina** [comment] 2021-08-23 04:24
@adam-collins is this deployed to test?, it's already reviewed and merged, once we confirm it is in  NCI test we can move it to the test column.

**Comment by peggynewman** [comment] 2021-08-24 03:36
A support queue issue was raised about this https://support.ehelp.edu.au/a/tickets/113564

Every so often I have checked to see how my observations were being harvested by the Atlas of Living Australia. I have done this by:
Clicking on Search and download records
Clicking on Simple Search
Entering my iNaturalist user name (peggydnew)

Doesn't work anymore

This is also functionality that's in the User Profiles, that uses this query, but I should raise that ticket over there:
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr1411&fq=alau_user_id:peggydnew

**Comment by nickdos** [comment] 2021-08-24 03:42
I think there may be a second issue here, which is the iNaturalists userID don't appear to be coming through anymore. 

Have a look at this record of yours @peggynewman - https://biocache.ala.org.au/occurrences/6bab7fd4-bcec-46ba-b484-eac0dba5446d

There is no mention of `peggydnew ` anywhere there. 

So maybe the data export we're using now no longer exports that field or possibly iNaturalist no longer exports it, as the settings seem to now indicate you provide a "public profile name" to your account, that might be used instead.

**Comment by peggynewman** [comment] 2021-08-24 04:03
Yeah, it ends up in raw_recordedBy

**Comment by nickdos** [comment] 2021-08-24 04:12
OK, so I think the issue is the mapping for the record view. The [JSON file](https://biocache.ala.org.au/ws/occurrences/6bab7fd4-bcec-46ba-b484-eac0dba5446d) also has no mention of `peggydnew`.

**Comment by peggynewman** [comment] 2021-08-24 04:34
Yeah I saw that. I'll open up the raw file from iNat and have a look.

**Comment by nickdos** [comment] 2021-08-24 04:36
Yeah - we need to debug this to know whether:

1. The userID is not being imported to the ALA, or
2. The UserID is being imported but its not being correctly mapped to the record JSON from SOLR index

**Comment by nickdos** [comment] 2021-08-24 05:55
SOLR appears to have `Peggy Newman` in the `raw_recordedBy` field: https://biocache.ala.org.au/ws/occurrences/search?q=text:%226bab7fd4-bcec-46ba-b484-eac0dba5446d%22&facets=raw_recordedBy&pageSize=0

```json
  "facetResults": [
    {
      "fieldName": "raw_recordedBy",
      "fieldResult": [
        {
          "label": "Peggy Newman",
          "i18nCode": "raw_recordedBy.Peggy Newman",
          "count": 1,
          "fq": "raw_recordedBy:\"Peggy Newman\""
        }
      ]
    }
  ]

**Comment by nickdos** [comment] 2021-08-24 07:16
@adam-collins has this fix been deployed to test site? When I look at `raw_recordedBy` vs `recordedBy`, my name is still not populated in `recordedBy` - whereas Peggy's name is present in both fields. See

https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=(raw_recordedBy:%22Nick%20dos%20Remedios%22%20OR%20raw_recordedBy:%22Peggy%20Newman%22)&facets=recordedBy,raw_recordedBy&pageSize=0

**Comment by nickdos** [comment] 2021-09-17 03:30
Schema change fixed this.

**Closed by nickdos** 2021-09-17 03:30 UTC
Labels: bug
