### ISSUE TITLE
Investigate difference in numbers for spatially valid

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#356] opened 2021-05-21 06:09 UTC
The number of records in production being excluded by the spatially valid (geospatial_kosher) flag is 2043
![image.png](https://images.zenhubusercontent.com/5823adcbe40e5714b170035c/36d5b1ad-824f-4e8b-be90-e7fed29f7896)

The number in quoll is 1 886 963
![image](https://user-images.githubusercontent.com/23368496/119091051-d0036c00-ba4f-11eb-953b-4b0f017b6b61.png)

This difference is partly to the following:
* Country coordinate mismatch - GBIF flags these as spatially invalid while we just provide a warning
Example: https://biocache-test.ala.org.au/occurrences/fc53b31c-9448-423b-9d9b-5bdb64511d1b The coordinates given fall on Christmas Island, the country given is Australia. While Christmas Island is an external territory of Australia, there is a separate ISO country code for Christmas Island recognised in the GADM layers. So this is producing a coordinates_country_mismatch issue which is included in the GBIF spatially invalid flag

* off shore sightings - where the Country was given as Australia but it was way off shore

* actually invalid country and country codes
Example: https://biocache-test.ala.org.au/occurrences/f619431b-6d25-4ce8-891b-7af029717e8c

However, there seem to be quite a few where the coordinates given are inside Australia's coastline, and I'm not sure why they are flagged as invalid
Example: https://biocache-test.ala.org.au/occurrences/ff255389-0a9a-4511-b457-b622a579933f - in this one the country is Australia and the continent is OCEANIA supplied as Australia which seems weird to me. Zooming in on the map the occurrence point is inside the Australian coastline - but the Data Quality checks includes the issue "Coordinates don't match supplied country"
Here's another one: https://biocache-test.ala.org.au/occurrences/f382ed52-a439-4a32-9019-82a84172fde0

**Comment by javier-molina** [comment] 2021-06-01 05:53
@RobinaSanderson 

This will go as part of the KB article at this stage, probably we need to catch up to clarify the details but is is essentially stating your analysis:

- Country coordinate mismatch is something that needs to be improved alongside GBIF to include Australian territories.
- Coastline sightings are a result of using layers with a coarse granularity, again a layer with better resolution needs to be used in a future version, this is will also be best addressed in collaboration with GBIF.

**Comment by djtfmartin** [comment] 2021-06-01 19:26
I've done some work for testing on this branch.
Most of the issues are caused by the gap between the country and EEZ layers. We can remediate this by adding a 10km buffer to country lookups.

https://github.com/gbif/pipelines/tree/357_records_dropped

**Comment by djtfmartin** [comment] 2021-06-05 06:38
Worked reviewed and merged in https://github.com/gbif/pipelines/pull/528

Current count of spatially invalid records = 207k

**Comment by nickdos** [comment] 2021-06-08 04:31
QA testing this issue. The difference between prod and pipelines is still quite a large amount - 2,043 vs 207,437, which is 2 orders of magnitude. 

The question is, is this close enough, considering the code base used is quite different?
I'm also questioning whether the prod value of 2,043 is legit, as it seems too low to me.

**Comment by nickdos** [comment] 2021-06-08 04:35
Something is wrong with prod DQ filters, as I now see a different breakdown (0 for spatially valid):

![image](https://user-images.githubusercontent.com/532845/121123542-bf802d80-c866-11eb-98d1-96302d765e09.png)

**Comment by nickdos** [comment] 2021-06-09 01:05
In the absence of reliable data from prod and given the fact that the assertions use completely different code, I think we should accept the numbers in test. 

@javier-molina your call to close or keep open.

**Comment by javier-molina** [comment] 2021-06-10 01:29
I'm happy numbers look in better shape than they did when the issue was originally raised.

**Closed** 2021-06-25 04:35 UTC
Labels: end-user-documentation, testing-findings
