### ISSUE TITLE
Add habitat values from IRMNG

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#36] opened 2020-03-16 22:14 UTC
Extracted from #26.

Needs detail added based on current biocache-store code.

**Comment by djtfmartin** [comment] 2020-05-08 10:43
This discussion on IRMNG is relevant in how we continue to manage this requirement

https://github.com/AtlasOfLivingAustralia/biocache-store/issues/375#issuecomment-618078102

**Comment by djtfmartin** [comment] 2020-09-02 14:04
This is a duplicate of #97

**Closed** 2020-09-08 05:26 UTC
Labels: duplicate
