### ISSUE TITLE
Feedback from Fauna Atlas NT and Flora Atlas NT

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#400] opened 2021-06-03 06:23 UTC
**Does the overall count of records look right to you?** 
Not really.

The URL below returns 1,415,900 Fauna Atlas NT records. 
The number of Fauna Atlas NT records that we last provided to the ALA was 1,026,020 records.
https://biocache-test.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr361%22)

The URL below returns 325,405 DNA AVH records (i.e. NT Herbarium specimens)
The number of NT Herbarium specimens totals approximately 276,981
https://biocache-test.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr15866%22)

The URL below returns 901,631 Flora Atlas NT records
The number of Flora Atlas NT records that we last provided to the NT last time was 949,700
https://biocache-test.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr362%22)

I did notice something a bit odd. Each of the three URLS provided above state there are 0 absence records, which is correct. However when combine in the URL below, there are 22,249 absence records. This doesn’t seem to make sense.
https://biocache-test.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr361%22%20OR%20data_resource_uid%3A%22dr362%22%20OR%20data_resource_uid%3A%22dr15866%22)

**Sensitive records - under the “Assertions” facet (on the left hand side), select any generalised records and check the Latitude, Longitude and Coordinates generalised  fields appear as expected.** 
Records do not appear as expected. We have a few species and a number of individual records that should be generalised. Miles Nicolls told us that data could not be generalised at the record level. He said that if there were records that needed to be generalised, then what ever species that record belonged to, the entire species would be generalised. One example is Ghost Bat (Macroderma gigas). On the production ALA website, all of our Ghost Bat records are generalised. In the test environment, there are five Ghost Bat records that are generalised – none of them are the records that we specified should be generalised.
For plant records, there are a number of our plant records that occur in WA that are generalised. Records state “Record is [sic] Western Australia in Sensitive. Generalised to 10km by WA DEC”. We did not specify that any of our plant records should be generalised. Unclear why WA DEC is generalising our data.
All records that have the assertion ‘already Generalised’ have not been. None of the data we give to the ALA have coordinates that are already generalised.

**Comment by peggynewman** [comment] 2021-06-03 06:28
We can resolve the record numbers by loading only the raw files in pipelines (csv on the upload server).

**Comment by javier-molina** [comment] 2021-06-03 06:29
@charvolant looks like apart from the record counts which now you have become an expert on there are some issues re:sensitive records.

Would you mind having a look at this please?

cc @peggynewman

**Comment by charvolant** [comment] 2021-06-04 00:01
Regarding the sensitive issue. 

For dr361 both production and test have 705 already generalised/437 generalised. The already generalised status comes about because the supplied lat/long are already less precise than what is required by the generalisation.

For dr15866 we have 1258 generalised in production and 1192 generalised/65 already generalised which are 1 off being comparable.

For dr362 we have 3 generalised and 41 already generalised records in production and 41 already generalised in test.

The three generalised records look like they should be generalised https://biocache.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr362%22)&disableAllQualityFilters=true&qualityProfile=ALA&fq=sensitive%3A%22generalised%22 However, the lat/long supplied appear to be utter tosh.

The records that have been generalised are in Western Australia or Queensland, so they are generalised by the rules of WA DEC, Queensland or wherever. Generalisation is based on the location of the record, not its collector.

**Comment by peggynewman** [comment] 2021-06-04 00:35
Interesting @charvolant I've just downloaded the source data from the uploads server and none of the 187 records have already generalised coordinates. So we need to reload the source data to check that it works. But also is this possibly indicative of a bigger problem?

**Comment by charvolant** [comment] 2021-06-04 01:07
@peggynewman alreadyGeneralised includes things which _appear_ to be already generalised. Much of the supplied data has lat/long only to a single decimal place and so will be marked as already generalised in both the production and pipelines systems. Feature? Bug? It's the same behaviour in both systems and gives similar numbers for sensitive data between the systems. IMHO, if we want to change it, we should do so later.

**Comment by charvolant** [comment] 2021-06-07 05:01
Attempting to load dr361 and dr362 from the original uploaded data.

dr361.zip is failing to be recognised as a DwCA, despite being assessed as OK by the GBIF DwCA validator. 

dr362.zip has 52461 duplicate catalog numbers. There seems to be no relation between the records with duploicates.

**Comment by charvolant** [comment] 2021-06-07 06:32
Original data for dr361 is encoded in Windows-1252. Has loaded correctly.

**Comment by charvolant** [comment] 2021-06-08 10:37
Data for dr362 loaded correctly. Requires a new id column to overcome composite key.

**Comment by javier-molina** [comment] 2021-06-10 04:45
I will close this as it is a duplicate of #410 let's continue the conversation there.

**Closed by javier-molina** 2021-06-10 04:45 UTC
Labels: collection-community-testing, duplicate, testing-findings
