### ISSUE TITLE
Location transform country code investigation

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#242] opened 2021-02-05 05:00 UTC
These questions were raised when looking into issues with assertions for the project reference group.

1.  UNKNOWN_COUNTRY assertion biocache and UNKNOWN_COUNTRY_NAME issue pipeline

Biocache currently inconsistently applies the UNKNOWN_COUNTRY assertion, this has raised the following questions about how the pipelines applies the UNKNOWN_COUNTRY_NAME assertion

Questions needing developer skills to find out:
- What list is used by pipelines to validate country names? Does it include ISO country code, Short name and Official name for each country? For example,
 https://www.iso.org/obp/ui/#search  provides only ISO country codes and short name
 https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes  provides Official name, Short name, Sovereignty, Codes
 https://unstats.un.org/unsd/geoinfo/ungegn/docs/11th-uncsgn-docs/E_Conf.105_13_CRP.13_15_UNGEGN%20WG%20Country%20Names%20Document.pdf provides most recent UN Official name, Short name, Codes
- If a short or common country name is provided, does it trigger this assertion?
- I assume an Official name won't trigger the assertion, but is that correct?
- Does searching on either the short name or the official name give the user access to records? or only on one or the other?

2.  COUNTRY_COORDINATE_MISMATCH assertion in biocache and COUNTRY_MISMATCH issue in pipelines

Biocache treats anything with an ISO country code as a country, this means off-shore territories of Australia are treated as countries and an assertion is raised where the supplied country is Australia and the coordinates belong to one of these off-shore territories. this raises the following questions for pipelines:

Developer question:
- Are off shore territories with their own ISO country codes treated as separate countries in pipelines? 

Business question:
- If off shore territories are treated as separate countries, do we want to override that for Australian offshore territories?

The following Australian off shore territories have ISO country codes:
- Christmas Island - code CX or CXR
- Cocos (Keeling) Islands - code CC or CCK
- Heard Island and MacDonald Islands - code HM or HMD
- Norfolk island - code NF or NFK
The following Australian off shore territories don't have ISO country codes:
- Ashmore and Cartier Islands
The Australian Antarctic Territory is included in the ISO code AQ or ATA which is for the area covered by the Antarctic treaty. This Australian territory is only recognised by 4 other countries, so it would make sense to use the Country name Antarctica rather than Australia for occurrence records from this area.

**Comment by RobinaSanderson** [comment] 2021-02-05 05:02
Hi @javier-molina - I've put both questions in the same issue, hopefully this makes sense. Let me know if needs to be rewritten.

**Comment by javier-molina** [comment] 2021-04-26 01:12
@djtfmartin this questions are still to be confirmed/addressed by @charvolant  I will move status back to In progress unless I hear otherwise from Doug.

**Comment by charvolant** [comment] 2021-05-03 04:58
Bottom line. The pipelines and biocache-store processing more-or-less matches but there are differences in issue names.

### biocache-store

UNKNOWN_COUNTRY_NAME in biocache-store is based on the `country` DwC field and will match any of the values in https://github.com/AtlasOfLivingAustralia/biocache-store/blob/develop/src/main/resources/countries.txt The full country name is used. Inverted lat/long and country/coordinate mismatches are then flagged based on the bounding boxes given in https://github.com/AtlasOfLivingAustralia/biocache-store/blob/develop/src/main/resources/countryCentrePoints.txt This occurs in https://github.com/AtlasOfLivingAustralia/biocache-store/blob/develop/src/main/scala/au/org/ala/biocache/processor/LocationProcessor.scala#L843

### pipelines

UNKNOWN_COUNTRY_NAME is present as an ALA issue code but never set

COUNTRY_INVALID is set by the GBIF location parser https://github.com/gbif/pipelines/blob/dev/sdks/core/src/main/java/org/gbif/pipelines/core/parsers/location/parser/LocationParser.java#L41 using the library GBIF country parser https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/CountryParser.java which uses the offical list of countries fromhttps://github.com/gbif/gbif-api/blob/dev/src/main/java/org/gbif/api/vocabulary/Country.java and an additional list in https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/countryName.tsv The country parser tries the bare country name, the formal name of the country and ISO 2- and 3-letter codes, with an optional prefix. (The additional country names seem to be an ad-hoc list of oddities that have turned up in GBIF data.)

The country code is also parsed using a CounytyCodeParser

If the country can be mapped onto the Country enum, it is considered valid. The `country` DwC term is set to the country title and the `countryCode` is set to the two-letter ISO code.

The LocationParser also attempts to check for negated lat/long, swapped coordinates and mismatches. This is handled by the location matcher https://github.com/gbif/pipelines/blob/dev/sdks/core/src/main/java/org/gbif/pipelines/core/parsers/location/parser/LocationMatcher.java and sets the PRESUMED_NEGATIVE_LATITUDE, PRESUMED_NEGATIVE_LONGITUDE and PRESUMED_SWAPPED_COORDINATE, COUNTRY_COORDINATE_MISMATCH and COUNTRY_DERIVED_FROM_COORDINATES issues.

If the country and country code do not match, a COUNTRY_MISMATCH issue is added.

**Comment by charvolant** [comment] 2021-05-03 05:12
The pipelines uses a GeocodeKVStore to match coordinates to country codes. SInce we have our own GeocodeKVStoreFactory, we can presumably use whatever layers suit us in terms of whether overseas territories are Australia or not. We may need to add an additional transform to the location matcher to flip the country/code if there is a mismatch.

The GBIF Country enum contains Christmas Island (CX or CXR), Cocos (Keeling) Islands (CC or CCK),  Heard Island and MacDonald Islands (HM or HMD), Norfolk island (NF or NFK). 

AQ/ATA is Antartica, with the various territories being rolled into AQ by the countryName table. 

The Ashmore and Cartier Islands are mapped onto Australia by the countryName table.

**Comment by RobinaSanderson** [comment] 2021-05-04 02:22
Thanks @charvolant - 
So looking at the country values in the vocabulary and the supplemental list, it looks like the main list used by GBIF is the ISO English short name and ISO country code. The supplemental list looks like an attempt to map everything else (I particularly like ("North South America" mapped to country code ZZ which looks likes the shorthand for "We don't recognise that").

If we use GBIF's spatial layers and the GBIF code, it will raise the issue/assertion COUNTRY_COORDINATE_MISMATCH if the coordinates are for Christmas Island and the Country and Country given are for Australia (AU).  

As you point out, we could diverge from GBIF and use a layer that specifies any coordinates in the off shore territories are matched to Australia and AU instead. I'm not sure whether we already have such a layer but there is this dataset: https://link.fsdf.org.au/dataset/abs-asgs-australia-boundary (linked through from Geoscience Australia). This might not be the format needed, however.

@javier-molina do you want to take this back to the reference group to see if they are willing to diverge from GBIF and for ALA to deal with the offshore territories as part of Australia? or is this something to deal with after go live?

**Comment by javier-molina** [comment] 2021-05-05 05:26
Thanks @charvolant and @RobinaSanderson for the analysis and interpretation of this functionality.

I prefer to bring this first to the attention of @peggynewman, @nickdos and @djtfmartin to see if there are strong opinions to go either way. If there is no consensus we can always take it to the reference group.

**Comment by nickdos** [comment] 2021-05-05 10:15
I think there might be a mismatch in concepts between ISO country codes and the concept of countries, which is usually tied to the exclusive economic zones (EEZ) associated with countries - they are different "things". I know GBIF uses a global EZZ layer to determine "countries" for the purposes of showing records for each country - [see Australia](https://www.gbif.org/country/AU/summary), which includes Norfolk and Heard islands. Another example would be Taiwan and China. Taiwan has its own country code but is part of China's EEZ.

I'd be surprised if GBIF haven't had to deal with this issue themselves...

**Comment by javier-molina** [comment] 2021-06-10 04:15
This has been sitting here for a while however the issue re: COUNTRY_COORDINATE_MISMATCH if the coordinates are for Christmas Island and the Country and Country given are for Australia (AU) has been addressed recently by #356

**Closed by javier-molina** 2021-06-10 04:16 UTC
Labels: gap, question
