### ISSUE TITLE
Species list indexing of authoritative lists only showing a single taxon in results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#523] opened 2022-03-07 23:09 UTC
Some authoritative species lists, which are indexed via Pipelines, are not showing the expected results in biocache. E.g. [the GRIIS list (dr9884)](https://lists.ala.org.au/speciesListItem/list/dr9884) has 3549 distinct taxa but the SOLR search using the DR shows only a single taxon being searched:

https://biocache.ala.org.au/occurrences/search?q=species_list_uid:dr9884

Returns only 101 records with a single taxon of _Acentrogobius pflaumii_.

Investigate why it is not returning records for all 3549 matched taxa.

**Comment by nickdos** [comment] 2022-03-07 23:11
CC: @peggynewman @djtfmartin @adam-collins

**Comment by peggynewman** [comment] 2022-03-09 05:44
Another species that's on this list that should return records for that query: https://biocache.ala.org.au/occurrences/search?q=lsid:https://id.biodiversity.org.au/node/apni/2904941#tab_recordsView 
eg  https://biocache.ala.org.au/occurrences/e347f854-c42f-43b6-97c0-30e6edf7beb9

**Comment by djtfmartin** [comment] 2022-03-16 15:10
Fix for this is on the pipelines side. The issue is line breaks in the CSVs that are downloaded from species lists tool.

PR for review here: https://github.com/gbif/pipelines/pull/691

**Comment by djtfmartin** [comment] 2022-09-05 12:25
fixed with https://github.com/gbif/pipelines/pull/691

**Closed as completed by djtfmartin** 2022-09-05 12:25 UTC
Labels: bug
