### ISSUE TITLE
Search UI - Assertions by user facet showing user code not name

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#411] opened 2021-06-08 07:09 UTC
**Steps to replicate:**
1. Search for all records in test environment
2. Click customise filters
3. In the Assertions section, select **Assertions by user**, and update

**Expected result**
Assertions by user facet group will display
Facets will display with the name of the user 

**Actual result**
**Assertions by user** facet group will display
Facets display with the code for the user

![image](https://user-images.githubusercontent.com/23368496/121139841-8bb00280-c87c-11eb-91b8-c4cda6f4d932.png)

Also looking at the picture above, in the facet group **Has user assertions** - I'm not sure why 2 records have user assertions "Not supplied" - is that missing a code for resolved assertions?

**Comment by javier-molina** [comment] 2021-06-09 01:06
@adam-collins, @brucehyslop  is this an i18n mapping issue? 

cc: @alexhuang091

**Comment by alexhuang091** [comment] 2021-06-09 01:21
I did some debug, prod vs test, the returned `label` in prod is translated to user name
<img width="472" alt="截屏2021-06-09 上午10 38 20" src="https://user-images.githubusercontent.com/61677987/121277831-c5344c80-c914-11eb-82c4-dcecbdbfaf01.png">
<img width="446" alt="截屏2021-06-09 上午10 42 57" src="https://user-images.githubusercontent.com/61677987/121277841-c9f90080-c914-11eb-8a38-e319965dca68.png">

**Comment by alexhuang091** [comment] 2021-06-09 03:52
We have this setting in `biocace-config.properties`:
`ansible/roles/biocache-properties/templates/biocache-config.properties:auth.substitution.fields=assertion_user_id,user_id,alau_user_id`

When we call `getFacetValueDisplayName("assertionUserId", "56528")` to translate the userid "56528" , we should go into this

```
        } else if (searchUtils.getAuthIndexFields().contains(facet)) {
            //if the facet field is collector or assertion_user_id we need to perform the substitution
            return authService.getDisplayNameFor(value);
        } 
```

This `getAuthIndexFields()` reads the configurtion and sees `assertionUserId` not in the list so `56528` doesn't get translated.

**Comment by alexhuang091** [comment] 2021-06-09 04:30
Should be fixed now. @RobinaSanderson please test

1. User name correctly displayed
2. No more `not supplied` (originally when you add an assertion and delete it, it will be categorized as 'Not supplied'. But now it should be in 'No assertions')

 user name and

**Comment by RobinaSanderson** [comment] 2021-06-09 04:58
Hi @alexhuang091 

I can confirm that most of the user names are shown in the test environment, however, there are still some that appear as codes:
![image](https://user-images.githubusercontent.com/23368496/121295583-a04ed200-c932-11eb-9b65-f244986884a3.png)

In addition, the number of assertions by user are higher than in production - I'm not sure why that would be? This is the same screen in prod: 
![image](https://user-images.githubusercontent.com/23368496/121295713-ddb35f80-c932-11eb-8384-b21ffe82601d.png)

Finally, in test when I display all values for Has user assertions, there are still 2 not supplied - do I need to refresh something to make these go away?
![image](https://user-images.githubusercontent.com/23368496/121295873-16533900-c933-11eb-86dd-ce71e64f52a6.png)

**Comment by alexhuang091** [comment] 2021-06-09 06:23
Hi Robina,

1. The largest userid in auth-test is 56563, those assertions were migrated from production database so have ids from prod server, which is available in test. So the code you saw are all larger than 56563. Nick is trying to sync 2 systems so we can check it again later. But it's not a bug.
2. still 2 'Not supplied'? This just needs Dave to do a new deployment. You can check it later.
3. I'm checking the number of assertions.

**Comment by alexhuang091** [comment] 2021-06-28 05:13
1. Nick didn't sync 2 systems so now still seeing userids in test, but it's not a bug. 
2. 'Not supplied' is fixed. 
3.  test has more user assertions than prod because we found and remapped some lost user assertions.

**Comment by javier-molina** [comment] 2021-06-28 10:25
I scrolled through all user assertions by user and found no more inconsistencies re: userids 

No assertions from screenshots above comes as Not supplied at the moment but I don't think that is a dealbreaker.


![Screen Shot 2021-06-28 at 8 22 59 pm](https://user-images.githubusercontent.com/8326394/123621695-d48d2280-d84e-11eb-9221-7797a54164d4.png)

**Closed** 2021-07-16 04:13 UTC
Labels: testing-findings
